packages:
  - "../configs/*"
  - "../ui"
  - "src/*"
allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
patchedDependencies:
  '@base-ui-components/react@1.0.0-rc.0': patches/@base-ui-components__react@1.0.0-rc.0.patch
  '@base-ui/react@1.3.0': patches/@base-ui__react@1.3.0.patch
